exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

# Site secttings
title: A Cool Design Project 
logourl: "/img/project-logo.svg" # Customize the top logo
baseurl: "/jekyll-design-projects"

# Build settings
markdown: kramdown
gems:
- jemoji
